
spring:
  application:
    name: Atlas-User-Service

  datasource:
    url: jdbc:postgresql://localhost:5432/atlas_userservice
    username: brunocase
    password: case

jpa:
  hibernate:
    ddl-auto: update
    show-sql: true
properties:
  hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

  security:
    oauth2:
      resourceserver:
        jwt:


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

api:
  security:
    token:
      secret: "OUJWeHM3OUJMPi80SzQ7O0tsQWFNZHtYOmopYWVJVFYK"

